import { USER_ROLE } from "@app/constants";
import { Product, UserResponse } from "@app/models";

export const LIST_CUSTOMERS: UserResponse[] = [
  {
    fullName: "Jane Cooper",
    role: USER_ROLE.ADMIN,
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: true,
    username: "admin",
    password: "123456",
    id: "1",
  },
  {
    fullName: "Floyd Miles",
    role: USER_ROLE.CONSUMER,
    company: "Yahoo",
    phoneNumber: "2055550100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: true,
    username: "consumer1",
    password: "123456",
    id: "2",
  },
  {
    fullName: "Ronald Richards",
    role: USER_ROLE.CONSUMER,
    company: "Adobe",
    phoneNumber: "3025550107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: false,
    username: "consumer2",
    password: "123456",
    id: "3",
  },
  {
    fullName: "Marvin McKinney0",
    role: USER_ROLE.CONSUMER,
    company: "Tesla0990",
    phoneNumber: "4356399000",
    email: "marvin@tesla.com",
    country: "Iran Ba 7",
    status: true,
    username: "consumer3",
    password: "123456",
    id: "4",
  },
  {
    fullName: "Jerome Bell",
    role: USER_ROLE.CONSUMER,
    company: "Google",
    phoneNumber: "6295550129",
    email: "jerome@google.com",
    country: "Réunion",
    status: true,
    username: "consumer4",
    password: "123456",
    id: "5",
  },
  {
    fullName: "Kathryn Murphy",
    role: USER_ROLE.CONSUMER,
    company: "Microsoft",
    phoneNumber: "4065550120",
    email: "kathryn@microsoft.com",
    country: "Réunion1100",
    status: true,
    username: "consumer5",
    password: "123456",
    id: "6",
  },
  {
    fullName: "Jacob Jones",
    role: USER_ROLE.CONSUMER,
    company: "Yahoo",
    phoneNumber: "2085550112",
    email: "jacob@yahoo.com",
    country: "Brazil00",
    status: false,
    username: "consumer6",
    password: "123456",
    id: "7",
  },
  {
    fullName: "Kristin Watson",
    role: USER_ROLE.CONSUMER,
    company: "Facebook",
    phoneNumber: "7045550127",
    email: "kristin@facebook.com",
    country: "Åland Islands09",
    status: false,
    username: "consumer7",
    password: "123456",
    id: "8",
  },
  {
    fullName: "Kim Ju Jon",
    role: USER_ROLE.CONSUMER,
    company: "Amazon",
    phoneNumber: "7045550566",
    email: "kimjujon@gamil.com",
    country: "korea",
    status: true,
    username: "consumer8",
    password: "123456",
    id: "9",
  },
  {
    fullName: "Kim12",
    role: USER_ROLE.CONSUMER,
    company: "Alibaba",
    phoneNumber: "5556667003",
    email: "donkihote123@gamil.com",
    country: "Adam Kho02",
    status: false,
    username: "consumer9",
    password: "123456",
    id: "10",
  },
  {
    fullName: "Minh",
    role: USER_ROLE.CONSUMER,
    company: "Amazon",
    phoneNumber: "0219323453",
    email: "mih@gmail.com",
    country: "Min",
    status: false,
    username: "minh453",
    password: "123456",
    id: "12",
  },
  {
    fullName: "mn",
    role: USER_ROLE.CONSUMER,
    company: "Facebook",
    phoneNumber: "3212132131",
    email: "mn@gmail.com",
    country: "2131",
    status: true,
    username: "mn131",
    password: "123456",
    id: "13",
  },
  {
    fullName: "user",
    role: USER_ROLE.CONSUMER,
    company: "Facebook",
    phoneNumber: "2051231234",
    email: "ac6679913@gmail.com",
    country: "Vietnam",
    status: false,
    username: "user234",
    password: "123456",
    id: "14",
  },
];

export const LIST_PRODUCT: Product[] = [
  {
    name: "Eggs",
    price: 83,
    quantity: 70,
    status: false,
    image: "https://i.ibb.co/2njpbkR/img1.jpg",
    code: "POD01",
    id: "1",
    userId: "1",
  },
  {
    name: "Hamburger",
    price: 32,
    quantity: 69,
    status: false,
    image: "https://i.ibb.co/CQKd125/img2.jpg",
    code: "POD02",
    id: "2",
    userId: "2",
  },
  {
    name: "Radio",
    price: 82,
    quantity: 66,
    status: true,
    image: "https://i.ibb.co/LCxXF3m/img3.jpg",
    code: "POD03",
    id: "3",
    userId: "3",
  },
  {
    name: "Cafe",
    price: 120,
    quantity: 177,
    status: true,
    image: "https://i.ibb.co/SKz9W6B/img4.jpg",
    code: "POD04",
    id: "4",
    userId: "4",
  },
  {
    name: "Banana",
    price: 42,
    quantity: 73,
    status: false,
    image: "https://i.ibb.co/KrDbWYN/img5.jpg",
    code: "POD05",
    id: "5",
    userId: "5",
  },
  {
    name: "Apple",
    price: 47,
    quantity: 90,
    status: true,
    image: "https://i.ibb.co/KWwvmwk/img6.jpg",
    code: "POD06",
    id: "6",
    userId: "6",
  },
  {
    name: "Cafe",
    price: 40,
    quantity: 19,
    status: false,
    image: "https://i.ibb.co/F32Tf81/img7.jpg",
    code: "POD07",
    id: "7",
    userId: "6",
  },
  {
    name: "Apple",
    price: 21,
    quantity: 29,
    status: false,
    image: "https://i.ibb.co/YBkm8VG/img8.jpg",
    code: "POD08",
    id: "9",
    userId: "8",
  },
  {
    name: "Banana",
    price: 210,
    quantity: 29,
    status: false,
    image: "https://i.ibb.co/nPTyCRZ/img9.jpg",
    code: "POD09",
    id: "10",
    userId: "8",
  },
  {
    name: "Onion",
    price: 12,
    quantity: 70,
    status: false,
    image: "https://i.ibb.co/vkbZPGr/img10.jpg",
    code: "POD10",
    id: "11",
    userId: "8",
  },
  {
    name: "Banana",
    price: 5,
    quantity: 3,
    status: false,
    image: "https://i.ibb.co/vkbZPGr/img10.jpg",
    code: "POD11",
    id: "13",
    userId: "3",
  },
  {
    name: "Cherry",
    price: 24,
    quantity: 50,
    status: false,
    image: "https://i.ibb.co/vkbZPGr/img10.jpg",
    code: "POD12",
    id: "14",
    userId: "7",
  },
  {
    name: "Orange",
    price: 30,
    quantity: 123,
    status: false,
    image: "https://i.ibb.co/vkbZPGr/img10.jpg",
    code: "POD13",
    id: "16",
    userId: "15",
  },
  {
    name: "Cafe",
    price: 12,
    quantity: 2,
    status: false,
    image: "https://i.ibb.co/vkbZPGr/img10.jpg",
    code: "POD14",
    id: "17",
    userId: "4",
  },
];
