import { USER_ROLE } from "../../../../constants";

export const LIST_CONTENT = [
  {
    fullName: "Jane Cooper",
    role: USER_ROLE.ADMIN,
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: true,
    username: "admin",
    password: "123456",
    id: "1",
  },
  {
    fullName: "Floyd Miles",
    role: USER_ROLE.CONSUMER,
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: false,
    username: "consumer1",
    password: "123456",
    id: "2",
  },
  {
    fullName: "Ronald Richards",
    role: USER_ROLE.CONSUMER,
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: false,
    username: "consumer2",
    password: "123456",
    id: "3",
  },
  {
    fullName: "Marvin McKinney",
    role: USER_ROLE.CONSUMER,
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: true,
    username: "consumer3",
    password: "123456",
    id: "4",
  },
  {
    fullName: "Jerome Bell",
    role: USER_ROLE.CONSUMER,
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: true,
    username: "consumer4",
    password: "123456",
    id: "5",
  },
  {
    fullName: "Kathryn Murphy",
    role: USER_ROLE.CONSUMER,
    company: "Micro",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Réunion",
    status: true,
    username: "consumer5",
    password: "123456",
    id: "6",
  },
  {
    fullName: "Jacob Jones",
    role: USER_ROLE.CONSUMER,
    company: "Amazon",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: true,
    username: "consumer6",
    password: "123456",
    id: "7",
  },
  {
    fullName: "Kristin Watson",
    role: USER_ROLE.CONSUMER,
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: false,
    username: "consumer7",
    password: "123456",
    id: "8",
  },
  {
    fullName: "Kris Leo",
    role: USER_ROLE.CONSUMER,
    company: "Facebook",
    phoneNumber: "(704) 555-0112",
    email: "krisleo@facebook.com",
    country: "Sahara",
    status: false,
    username: "consumer7",
    password: "123456",
    id: "9",
  },
];
