export const LIST_CONTENT_PRODUCT = [
  {
    name: "Eggs",
    price: 83,
    quantity: 70,
    status: false,
    image: "/src/libs/ui/images/img1.jpg",
    code: "POD1",
    id: "1",
    userId: "1",
  },
  {
    name: "Hamburger",
    price: 32,
    quantity: 69,
    status: false,
    image: "/src/libs/ui/images/img2.jpg",
    code: "POD2",
    id: "2",
    userId: "2",
  },
  {
    name: "Radio",
    price: 82,
    quantity: 66,
    status: true,
    image: "/src/libs/ui/images/img3.jpg",
    code: "POD3",
    id: "3",
    userId: "3",
  },
  {
    name: "Coffee",
    price: 49,
    quantity: 17,
    status: true,
    image: "/src/libs/ui/images/img4.jpg",
    code: "POD4",
    id: "4",
    userId: "4",
  },
  {
    name: "Hat",
    price: 42,
    quantity: 73,
    status: false,
    image: "/src/libs/ui/images/img5.jpg",
    code: "POD5",
    id: "5",
    userId: "5",
  },
  {
    name: "Volleyball",
    price: 47,
    quantity: 9,
    status: true,
    image: "/src/libs/ui/images/img6.jpg",
    code: "POD6",
    id: "6",
    userId: "6",
  },
  {
    name: "Honey",
    price: 39,
    quantity: 7,
    status: false,
    image: "/src/libs/ui/images/img7.jpg",
    code: "POD7",
    id: "7",
    userId: "6",
  },
  {
    name: "Tomate",
    price: 20,
    quantity: 44,
    status: true,
    image: "/src/libs/ui/images/img8.jpg",
    code: "POD8",
    id: "8",
    userId: "8",
  },
  {
    name: "KungFu",
    price: 21,
    quantity: 29,
    status: false,
    image: "/src/libs/ui/images/img9.jpg",
    code: "POD9",
    id: "9",
    userId: "8",
  },
  {
    name: "Karate",
    price: 59,
    quantity: 44,
    status: true,
    image: "/src/libs/ui/images/img10.jpg",
    code: "POD10",
    id: "10",
    userId: "8",
  },
  {
    name: "Bana",
    price: 6,
    quantity: 35,
    status: true,
    image: "/src/libs/ui/images/img10.jpg",
    code: "POD11",
    id: "11",
    userId: "6",
  },
];

export const LIST_CONTENT_PRODUCT_PAGE1 = [
  {
    name: "Eggs",
    price: 83,
    quantity: 70,
    status: false,
    image: "/src/libs/ui/images/img1.jpg",
    code: "POD1",
    id: "1",
    userId: "1",
  },
  {
    name: "Hamburger",
    price: 32,
    quantity: 69,
    status: false,
    image: "/src/libs/ui/images/img2.jpg",
    code: "POD2",
    id: "2",
    userId: "2",
  },
  {
    name: "Radio",
    price: 82,
    quantity: 66,
    status: true,
    image: "/src/libs/ui/images/img3.jpg",
    code: "POD3",
    id: "3",
    userId: "3",
  },
  {
    name: "Coffee",
    price: 49,
    quantity: 17,
    status: true,
    image: "/src/libs/ui/images/img4.jpg",
    code: "POD4",
    id: "4",
    userId: "4",
  },
  {
    name: "Hat",
    price: 42,
    quantity: 73,
    status: false,
    image: "/src/libs/ui/images/img5.jpg",
    code: "POD5",
    id: "5",
    userId: "5",
  },
  {
    name: "Volleyball",
    price: 47,
    quantity: 9,
    status: true,
    image: "/src/libs/ui/images/img6.jpg",
    code: "POD6",
    id: "6",
    userId: "6",
  },
  {
    name: "Honey",
    price: 39,
    quantity: 7,
    status: false,
    image: "/src/libs/ui/images/img7.jpg",
    code: "POD7",
    id: "7",
    userId: "6",
  },
  {
    name: "Tomate",
    price: 20,
    quantity: 44,
    status: true,
    image: "/src/libs/ui/images/img8.jpg",
    code: "POD8",
    id: "8",
    userId: "8",
  },
  {
    name: "KungFu",
    price: 21,
    quantity: 29,
    status: false,
    image: "/src/libs/ui/images/img9.jpg",
    code: "POD9",
    id: "9",
    userId: "8",
  },
  {
    name: "Karate",
    price: 59,
    quantity: 44,
    status: true,
    image: "/src/libs/ui/images/img10.jpg",
    code: "POD10",
    id: "10",
    userId: "8",
  },
];
export const LIST_CONTENT_PRODUCT_PAGE2 = [
  {
    name: "Bana",
    price: 6,
    quantity: 35,
    status: true,
    image: "/src/libs/ui/images/img10.jpg",
    code: "POD11",
    id: "11",
    userId: "6",
  },
];
